## Importing necessary packages

In [34]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
# make_pipeline it automatically names each step in the pipeline with lowercase versions of the class names. This eliminates the need to explicitly provide names for each step in the pipeline.
from sklearn.pipeline import make_pipeline 
from sklearn.metrics import classification_report, confusion_matrix

In [35]:
# Reading the data set
df = pd.read_csv("I://SSSK//Data Science-D55//Project - GUVI//Final project//Car_Class//cars_class(copy.csv")
df

,ID,Comp,Circ,D.Circ,Rad.Ra,Pr.Axis.Ra,Max.L.Ra,Scat.Ra,Elong,Pr.Axis.Rect,Max.L.Rect,Sc.Var.Maxis,Sc.Var.maxis,Ra.Gyr,Skew.Maxis,Skew.maxis,Kurt.maxis,Kurt.Maxis,Holl.Ra,Class
0,1,88,39,70,166,66,7,148,44,19,134,167,332,143,69,5,13,193,201,0
1,2,85,35,64,129,57,6,116,57,17,125,138,200,123,65,1,23,196,203,3
2,3,91,41,84,141,57,9,149,45,19,143,170,330,158,72,9,14,189,199,3
3,4,102,54,98,177,56,10,219,31,25,171,219,706,223,72,5,17,186,196,1
4,5,87,39,74,152,58,6,151,44,19,136,174,337,140,70,1,33,187,196,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714,715,111,58,105,183,51,6,265,26,29,174,285,1018,255,85,4,8,181,183,0
715,716,93,43,76,149,57,7,149,44,19,143,172,335,176,69,14,0,189,194,2
716,717,90,42,63,144,59,7,131,50,18,142,154,259,162,65,15,3,197,204,3
717,718,101,56,101,231,72,10,217,31,24,171,232,698,216,72,2,6,187,197,2
718,719,99,38,74,184,66,6,164,39,20,131,193,414,137,71,2,22,200,202,0

In [7]:
#Statistics of the dataset
df.describe()

,ID,Comp,Circ,D.Circ,Rad.Ra,Pr.Axis.Ra,Max.L.Ra,Scat.Ra,Elong,Pr.Axis.Rect,Max.L.Rect,Sc.Var.Maxis,Sc.Var.maxis,Ra.Gyr,Skew.Maxis,Skew.maxis,Kurt.maxis,Kurt.Maxis,Holl.Ra,Class
count,719.000000,719.000000,719.000000,719.000000,719.000000,719.000000,719.000000,719.000000,719.000000,719.000000,719.000000,719.000000,719.000000,719.000000,719.000000,719.000000,719.000000,719.000000,719.000000,719.000000
mean,360.000000,93.435327,44.851182,81.723227,168.579972,61.847010,8.625869,168.137691,41.075104,20.531293,148.030598,188.168289,436.215577,174.726008,72.682893,6.343533,12.394993,188.798331,195.407510,1.470097
std,207.701709,8.111406,6.150286,15.528208,33.809172,8.259136,4.916908,32.937591,7.764459,2.560969,14.560092,31.235395,174.964977,32.149568,7.542055,4.856169,8.742511,6.048522,7.235166,1.126477
min,1.000000,73.000000,33.000000,40.000000,105.000000,47.000000,2.000000,112.000000,26.000000,17.000000,118.000000,130.000000,184.000000,109.000000,59.000000,0.000000,0.000000,176.000000,181.000000,0.000000
25%,180.500000,87.000000,40.000000,70.000000,141.000000,57.000000,6.000000,146.000000,33.000000,19.000000,137.000000,167.000000,317.000000,149.000000,68.000000,2.000000,5.500000,184.000000,190.000000,0.000000
50%,360.000000,93.000000,44.000000,79.000000,166.000000,61.000000,8.000000,157.000000,43.000000,20.000000,146.000000,178.000000,362.000000,174.000000,72.000000,6.000000,11.000000,188.000000,196.000000,1.000000
75%,539.500000,99.000000,49.000000,96.000000,194.500000,65.000000,10.000000,197.500000,46.000000,23.000000,159.000000,216.000000,584.500000,198.000000,76.000000,9.000000,18.000000,193.000000,201.000000,2.000000
max,719.000000,119.000000,59.000000,110.000000,333.000000,138.000000,55.000000,265.000000,61.000000,29.000000,188.000000,320.000000,1018.000000,262.000000,135.000000,22.000000,41.000000,204.000000,211.000000,3.000000

##### Findings: Almost all variables exhibit a normal distribution, a conclusion drawn from examining their mean, standard deviation, minimum, and maximum values.

In [36]:
#Displaying the names of all columns or features to identify any potential absence in the statistical output.
df.columns

Index(['ID', 'Comp', 'Circ', 'D.Circ', 'Rad.Ra', 'Pr.Axis.Ra', 'Max.L.Ra',
       'Scat.Ra', 'Elong', 'Pr.Axis.Rect', 'Max.L.Rect', 'Sc.Var.Maxis',
       'Sc.Var.maxis', 'Ra.Gyr', 'Skew.Maxis', 'Skew.maxis', 'Kurt.maxis',
       'Kurt.Maxis', 'Holl.Ra', 'Class'],
      dtype='object')

##### All the columns or features listed above are included in the statistics, indicating that they exclusively consist of only numerical data types (integers or floats).

In [37]:
# Examining the dataset to identify any null values and obtain the data types of each feature.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 719 entries, 0 to 718
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            719 non-null    int64
 1   Comp          719 non-null    int64
 2   Circ          719 non-null    int64
 3   D.Circ        719 non-null    int64
 4   Rad.Ra        719 non-null    int64
 5   Pr.Axis.Ra    719 non-null    int64
 6   Max.L.Ra      719 non-null    int64
 7   Scat.Ra       719 non-null    int64
 8   Elong         719 non-null    int64
 9   Pr.Axis.Rect  719 non-null    int64
 10  Max.L.Rect    719 non-null    int64
 11  Sc.Var.Maxis  719 non-null    int64
 12  Sc.Var.maxis  719 non-null    int64
 13  Ra.Gyr        719 non-null    int64
 14  Skew.Maxis    719 non-null    int64
 15  Skew.maxis    719 non-null    int64
 16  Kurt.maxis    719 non-null    int64
 17  Kurt.Maxis    719 non-null    int64
 18  Holl.Ra       719 non-null    int64
 19  Class         719 non-null    int64
dtypes: int64(20)
memory usage: 112.5 KB

##### Findings: Fortunately, all features have integer data types, and no null values were found.

## Creating the model (LogisticRegression)

In [11]:
# Separating features (X) and the target variable (y) from the DataFrame
# The 'ID' feature holds no informative value as it solely serves as an index. Therefore, we can exclude it from the dataframe before fitting it to the model.

X = df.drop(['ID', 'Class'], axis=1)
y = df['Class']

In [12]:
# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
# Applying the optimal hyperparameters obtained through the 'RandomizedSearchCV' method. The complete code provided at the end of this page.
best_hyperparameters = {'penalty': 'l2', 'class_weight': None, 'C': 29.763514416313132}

In [14]:
# Constructing a pipeline with scaling and logistic regression using the optimal hyperparameters obtained through the 'RandomizedSearchCV' method.
# make_pipeline automatically names each step in the pipeline with lowercase versions of the class names. This eliminates the need to explicitly provide names for each step in the pipeline.

model = make_pipeline(StandardScaler(), LogisticRegression(solver='lbfgs', max_iter=5000, **best_hyperparameters))

In [15]:
# Fitting the model to the scaled training dataset.
model.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression',
                 LogisticRegression(C=29.763514416313132, max_iter=5000))])

## Test set prediction results

In [16]:
# Evaluating the model on the scaled test set

test_accuracy = model.score(X_test, y_test)
print("\nTest Accuracy:", test_accuracy)

Test Accuracy: 0.7916666666666666

In [32]:
## Classification report for the test set

# Defining the actual class names
class_names = ['bus', 'Opel Manta', 'Saab', 'Van']

# Classification report for the test set
class_rep_test = classification_report(y_test, model.predict(X_test), target_names=class_names)

print("\nClassification Report (Test Set):")
print(class_rep_test)

Classification Report (Test Set):
              precision    recall  f1-score   support

         bus       1.00      0.97      0.99        35
  Opel Manta       0.67      0.55      0.60        40
        Saab       0.59      0.71      0.64        34
         Van       0.94      0.97      0.96        35

    accuracy                           0.79       144
   macro avg       0.80      0.80      0.80       144
weighted avg       0.80      0.79      0.79       144

In [26]:
## Confusion matrix for the test set

conf_matrix_test = confusion_matrix(y_test, model.predict(X_test))

# Defining the actual class names
class_names = ['bus', 'Opel Manta', 'Saab', 'Van']

# Create a DataFrame for the confusion matrix with rows and column names
conf_matrix_df_test = pd.DataFrame(conf_matrix_test, 
                                   index=class_names, 
                                   columns=class_names)

print("\nConfusion Matrix (Test Set):")
print(conf_matrix_df_test)

Confusion Matrix (Test Set):
            bus  Opel Manta  Saab  Van
bus          34           0     0    1
Opel Manta    0          22    17    1
Saab          0          10    24    0
Van           0           1     0   34

## Training set prediction results

In [17]:
# Evaluating the model on the scaled training set

train_accuracy = model.score(X_train, y_train)
print("Train Accuracy:", train_accuracy)

Train Accuracy: 0.8556521739130435

In [33]:
## Classification report for the training set

# Defining the actual class names
class_names = ['bus', 'Opel Manta', 'Saab', 'Van']

# Classification report for the training set
class_rep_train = classification_report(y_train, model.predict(X_train), target_names=class_names)

print("\nClassification Report (Training Set):")
print(class_rep_train)

Classification Report (Training Set):
              precision    recall  f1-score   support

         bus       0.97      0.98      0.98       154
  Opel Manta       0.73      0.72      0.73       140
        Saab       0.71      0.71      0.71       139
         Van       0.99      0.99      0.99       142

    accuracy                           0.86       575
   macro avg       0.85      0.85      0.85       575
weighted avg       0.85      0.86      0.86       575

In [29]:
# Confusion matrix for the training set

conf_matrix_train = confusion_matrix(y_train, model.predict(X_train))

# Defining the actual class names
class_names = ['bus', 'Opel Manta', 'Saab', 'Van']

# Create a DataFrame for the confusion matrix with rows and column names
conf_matrix_df_train = pd.DataFrame(conf_matrix_train, 
                                   index=class_names, 
                                   columns=class_names)

print("\nConfusion Matrix (Training Set):")
print(conf_matrix_df_train)

Confusion Matrix (Training Set):
            bus  Opel Manta  Saab  Van
bus         151           0     2    1
Opel Manta    1         101    38    0
Saab          2          37    99    1
Van           1           0     0  141

## Conclusion

##### I have experimented with various methods, including Decision Tree, Random Forest, XGBoost, and found that only Logistic Regression yielded the highest prediction accuracy.

##### I attempted feature engineering to identify the optimal features for the model and discovered that the best feature does not contribute to any improvement in the model's accuracy.

### Code with randomized search, in case we want to explore how the optimal parameters were determined.

In [ ]:
# import pandas as pd
# from sklearn.linear_model import LogisticRegression
# from sklearn.model_selection import RandomizedSearchCV, train_test_split
# from sklearn.preprocessing import StandardScaler
# from sklearn.pipeline import make_pipeline
# from sklearn.metrics import classification_report, confusion_matrix
# import numpy as np

# df = pd.read_csv("I://SSSK//Data Science-D55//Project - GUVI//Final project//Car_Class//cars_class(copy.csv")
# X = df.drop(['ID', 'Class'], axis=1)
# y = df['Class']

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# model = make_pipeline(StandardScaler(), LogisticRegression(solver='lbfgs', max_iter=5000))

# param_dist = {
#     'logisticregression__penalty': ['l2'],
#     'logisticregression__C': np.logspace(-4, 4, 20),
#     'logisticregression__class_weight': [None, 'balanced'],
# }

# random_search = RandomizedSearchCV(estimator=model, param_distributions=param_dist, 
#                                    n_iter=10, cv=5, scoring='accuracy', random_state=42)

# random_search.fit(X_train, y_train)

# print("Best Hyperparameters:", random_search.best_params_)

# test_accuracy = random_search.best_estimator_.score(X_test, y_test)
# print("\nTest Accuracy:", test_accuracy)

# train_accuracy = random_search.best_estimator_.score(X_train, y_train)
# print("Train Accuracy:", train_accuracy)

# class_rep_test = classification_report(y_test, random_search.best_estimator_.predict(X_test))
# print("\nClassification Report (Test Set):")
# print(class_rep_test)

# class_rep_train = classification_report(y_train, random_search.best_estimator_.predict(X_train))
# print("\nClassification Report (Training Set):")
# print(class_rep_train)

# conf_matrix_test = confusion_matrix(y_test, random_search.best_estimator_.predict(X_test))
# print("\nConfusion Matrix (Test Set):")
# print(conf_matrix_test)

# conf_matrix_train = confusion_matrix(y_train, random_search.best_estimator_.predict(X_train))
# print("\nConfusion Matrix (Training Set):")
# print(conf_matrix_train)